# Site settings
title: object.io
subtitle: All code has costs. Only some code has value.
author: Laust Rud Jacobsen
email: work@object.io
description: >
  Hi, I'm Laust Rud Jacobsen, a freelance webapp developer
  specializing in Ruby on Rails. Hire me to build awesome
  stuff for you.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "https://object.io" # the base hostname & protocol for your site
url: "https://object.io" # the base hostname & protocol for your site
twitter_username: laustrud
github_username:  rud

# Build settings
markdown: kramdown
permalink: "/site/:year/:title/"
paginate: 2 # for the frontpage
paginate_path: "/blog/page:num"
